### PR TITLE
fix: make sure borders are accounted for when calculating the slider …

### LINKED ISSUE #152: Thumb size/offset does not take in account the border of the thumb
Hello,

when I'm adding a 1px border to the thumb, the calculated offset if the thumb only taking the width value without the border. 

gist exemple : https://gist.github.com/hugomassing/156eef503df8ba7d1a087eb36353de03

### PR DESCRIPTION
**Pull request by stonebk**
…size

Fixes #152

### CODE REVIEW

File: src/styleguidist/ThemeWrapper.jsx [hunk 1]
```diff
@@ -22,6 +22,8 @@ const GlobalStyle = createGlobalStyle`
         background-color: black;
         color: white;
         cursor: pointer;
+        border: 5px solid gray;
```
Comment (stonebk) [inline src/styleguidist/ThemeWrapper.jsx:25]: Updated examples to include a border to surface this issue.
